services: 
  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  drf:
    env_file:
      - ./.env.dev
    build: ./backend
    command: gunicorn dsam.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/backend/staticfiles
    depends_on:
      - db
    expose:
      - 8000

  njs_client:
    build: front
    depends_on:
      - db
    expose:
      - 3000

  nginx:
    image: nginx
    build: 
      context: ./deployment/nginx/
    restart: always
    volumes:
      - static_volume:/usr/src/backend/staticfiles
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - drf
      - njs_client
    ports:
    - 80:80
    - 443:433
  
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email chekhonins@gmail.com --agree-tos --no-eff-email -d dancesport.am

volumes:
  postgres_data:
  static_volume:

