# Generated by Django 4.1.7 on 2023-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_for_next', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
