# Generated by Django 4.1.7 on 2023-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_for_next', '0002_feedback_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
