name: Build&Test on dispatch #запусуск по нажатию
on:
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Print workdir
      run: |
        pwd
        ls